constants:
    # Quantum/Timeslice length in ms
    QUANTUM: 100
    # Real-time clock frequency
    CLK_FREQ: 16000
    # Address of mtime and mtimecmp registers
    MTIME: 0x200bff8UL
    MTIMECMP: 0x2004000UL


# Process configurations
# regs: Initial register values
#   pc: Initial program counter
#   ...
# pmp: Physical Memory Protection
#   rwx:     Read, write and execute permissions.
#   base:    Base address of memory region, must be aligned with 2^lsize.
#   lg_size: log_2(Size of memory region).
processes:
    - regs.pc: 0x20100000
      pmp:
          - {rwx: rx, base: 0x20100000, lg_size: 20}
          - {rwx: rw, base: 0x80001000, lg_size: 12}
          - {rwx: rw, base: 0x10012000, lg_size: 12}
          - {rwx: rw, base: 0x10013000, lg_size: 12}
    - regs.pc: 0x20200000
      pmp:
          - {rwx: rx, base: 0x20200000, lg_size: 20}
          - {rwx: rw, base: 0x80002000, lg_size: 12}
