constants:
    # Quantum/Timeslice length in ms
    QUANTUM: 100
    # Real-time clock frequency
    CLK_FREQ: 16000
    # Address of mtime and mtimecmp registers
    MTIME: 0x200bff8UL
    MTIMECMP: 0x2004000UL


# Process configurations
# PC: Initial program counter
# PMP: Physical Memory Protection
#     We supports at most eight PMP regions and only
#     the NA4/NAPOT type PMP configuration.
#     rwx: Read, write and execute permissions.
#     base: Base address of memory region.
#     size: log_2(size of region in bytes)
processes:
    - pc: 0x20100000
      pmp:
          - {rwx: rx, base: 0x20100000, size: 20}
          - {rwx: rw, base: 0x80001000, size: 12}
          - {rwx: rw, base: 0x10012000, size: 12}
          - {rwx: rw, base: 0x10013000, size: 12}
    - pc: 0x20200000
      pmp:
          - {rwx: rx, base: 0x20200000, size: 20}
          - {rwx: rw, base: 0x80002000, size: 12}
