#ifndef _GR_OFFSET_H
#define _GR_OFFSET_H
#include "util.h"

#define GR_PC   (REG_SIZE * 0)
#define GR_RA   (REG_SIZE * 1)
#define GR_SP   (REG_SIZE * 2)
#define GR_GP   (REG_SIZE * 3)
#define GR_TP   (REG_SIZE * 4)
#define GR_T0   (REG_SIZE * 5)
#define GR_T1   (REG_SIZE * 6)
#define GR_T2   (REG_SIZE * 7)
#define GR_S0   (REG_SIZE * 8)
#define GR_S1   (REG_SIZE * 9)
#define GR_A0   (REG_SIZE * 10)
#define GR_A1   (REG_SIZE * 11)
#define GR_A2   (REG_SIZE * 12)
#define GR_A3   (REG_SIZE * 13)
#define GR_A4   (REG_SIZE * 14)
#define GR_A5   (REG_SIZE * 15)
#define GR_A6   (REG_SIZE * 16)
#define GR_A7   (REG_SIZE * 17)
#define GR_S2   (REG_SIZE * 18)
#define GR_S3   (REG_SIZE * 19)
#define GR_S4   (REG_SIZE * 20)
#define GR_S5   (REG_SIZE * 21)
#define GR_S6   (REG_SIZE * 22)
#define GR_S7   (REG_SIZE * 23)
#define GR_S8   (REG_SIZE * 24)
#define GR_S9   (REG_SIZE * 25)
#define GR_S10  (REG_SIZE * 26)
#define GR_S11  (REG_SIZE * 27)
#define GR_T3   (REG_SIZE * 28)
#define GR_T4   (REG_SIZE * 29)
#define GR_T5   (REG_SIZE * 30)
#define GR_T6   (REG_SIZE * 31)

#endif /* _GR_OFFSET_H */
